In [1]:
#Prediction of cpu utilization 
import pandas as pd
from sklearn import linear_model
df=pd.read_csv("overallinfo.csv")

In [2]:
df

,Tue Dec 1 17:06:23 2020,7.000000,139420,124233,552,1937853,40.000000,1233236,2035520,90544,...,46752,17724,22636,9445613,0,0.1,0.2,0.3,0.4,0.5
0,Tue Dec 1 17:06:23 2020,7.0,139420,124233,552,1937853,40.0,1233236,2035520,90544,...,46752,17724,22636,9445613,0,0,0,0,0,0
1,Tue Dec 1 17:06:23 2020,7.0,139420,124233,552,1937853,40.0,1233236,2035520,90544,...,46752,17724,22636,9445613,0,0,0,0,0,0
2,Tue Dec 1 17:06:23 2020,7.0,139420,124233,552,1937853,40.0,1233236,2035520,90544,...,46752,17724,22636,9445613,0,0,0,0,0,0
3,Tue Dec 1 17:06:23 2020,7.0,139420,124233,552,1937853,40.0,1233236,2035520,90544,...,46752,17724,22636,9445613,5845,0,0,0,112,112
4,Tue Dec 1 17:07:01 2020,7.0,139824,124602,552,1940893,40.0,1231924,2035520,89520,...,46596,17676,22380,9456123,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329,Tue Dec 1 19:27:34 2020,9.0,235595,210175,568,2677591,46.0,1111332,2035520,608668,...,44020,17236,152167,13611835,0,0,0,0,0,0
330,Tue Dec 1 19:27:34 2020,9.0,235595,210175,568,2677591,46.0,1111332,2035520,608668,...,44020,17236,152167,13611835,0,0,0,0,0,0
331,Tue Dec 1 19:27:34 2020,9.0,235595,210175,568,2677591,46.0,1111332,2035520,608668,...,44020,17236,152167,13611835,0,0,0,0,0,0
332,Tue Dec 1 19:27:34 2020,9.0,235595,210175,568,2677591,46.0,1111332,2035520,608668,...,44020,17236,152167,13611835,4564,0,0,8,1332,1340
333,Tue Dec 1 19:27:34 2020,9.0,235612,210189,568,2678068,46.0,1111320,2035520,608668,...,44020,17236,152102,13616399,0,0,0,0,0,0

In [3]:
column_names=["time","cpu_utilization","processor_time","user_time","nice_time","idle_time","memory_utilization","used_mem","total_mem","free_mem","available_mem","pagetable","vmused","num_pages","pf_before","pf_persec","ps_in_persec","ps_out_psec","pread_persec","pwrite_persec","p_persec"]
df=pd.read_csv("overallinfo.csv",names=column_names)

In [4]:
df

,time,cpu_utilization,processor_time,user_time,nice_time,idle_time,memory_utilization,used_mem,total_mem,free_mem,...,pagetable,vmused,num_pages,pf_before,pf_persec,ps_in_persec,ps_out_psec,pread_persec,pwrite_persec,p_persec
0,Tue Dec 1 17:06:23 2020,7.0,139420,124233,552,1937853,40.0,1233236,2035520,90544,...,46752,17724,22636,9445613,0,0,0,0,0,0
1,Tue Dec 1 17:06:23 2020,7.0,139420,124233,552,1937853,40.0,1233236,2035520,90544,...,46752,17724,22636,9445613,0,0,0,0,0,0
2,Tue Dec 1 17:06:23 2020,7.0,139420,124233,552,1937853,40.0,1233236,2035520,90544,...,46752,17724,22636,9445613,0,0,0,0,0,0
3,Tue Dec 1 17:06:23 2020,7.0,139420,124233,552,1937853,40.0,1233236,2035520,90544,...,46752,17724,22636,9445613,0,0,0,0,0,0
4,Tue Dec 1 17:06:23 2020,7.0,139420,124233,552,1937853,40.0,1233236,2035520,90544,...,46752,17724,22636,9445613,5845,0,0,0,112,112
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
330,Tue Dec 1 19:27:34 2020,9.0,235595,210175,568,2677591,46.0,1111332,2035520,608668,...,44020,17236,152167,13611835,0,0,0,0,0,0
331,Tue Dec 1 19:27:34 2020,9.0,235595,210175,568,2677591,46.0,1111332,2035520,608668,...,44020,17236,152167,13611835,0,0,0,0,0,0
332,Tue Dec 1 19:27:34 2020,9.0,235595,210175,568,2677591,46.0,1111332,2035520,608668,...,44020,17236,152167,13611835,0,0,0,0,0,0
333,Tue Dec 1 19:27:34 2020,9.0,235595,210175,568,2677591,46.0,1111332,2035520,608668,...,44020,17236,152167,13611835,4564,0,0,8,1332,1340
334,Tue Dec 1 19:27:34 2020,9.0,235612,210189,568,2678068,46.0,1111320,2035520,608668,...,44020,17236,152102,13616399,0,0,0,0,0,0

In [5]:
df.dtypes

time                   object
cpu_utilization       float64
processor_time          int64
user_time               int64
nice_time               int64
idle_time               int64
memory_utilization    float64
used_mem                int64
total_mem               int64
free_mem                int64
available_mem           int64
pagetable               int64
vmused                  int64
num_pages               int64
pf_before               int64
pf_persec               int64
ps_in_persec            int64
ps_out_psec             int64
pread_persec            int64
pwrite_persec           int64
p_persec                int64
dtype: object

In [6]:
df=df.drop(["time","memory_utilization","used_mem","total_mem","free_mem","available_mem","pagetable","vmused","num_pages","pf_before","pf_persec","ps_in_persec","ps_out_psec","pread_persec","pwrite_persec","p_persec"],axis=1)

In [7]:
df_copy=df.copy()
training_data=df_copy.sample(frac=0.75)
test_data=df_copy.drop(training_data.index)

In [8]:
training_data

     cpu_utilization  processor_time  user_time  nice_time  idle_time
16               7.0          139853     124626        552    1941854
265              8.0          186069     165934        560    2344184
116              7.0          142220     126740        552    1998499
246              7.0          143457     127848        552    2016106
94               7.0          141056     125688        552    1969400
..               ...             ...        ...        ...        ...
162              7.0          142507     126976        552    2008626
321              8.0          216377     193216        560    2633423
68               7.0          140930     125593        552    1961579
20               7.0          139866     124635        552    1942336
271              8.0          187512     167208        560    2366432

[251 rows x 5 columns]

In [9]:
X=training_data[["processor_time","user_time","nice_time","idle_time"]]
y=training_data["cpu_utilization"]

In [10]:
reg=linear_model.LinearRegression()

In [11]:
reg.fit(X,y)

LinearRegression()

In [12]:
test_data=test_data.drop(["cpu_utilization"],axis=1)

In [13]:
prediction=reg.predict(test_data)

In [14]:
prediction

array([7.01191725, 7.01054557, 7.01054557, 7.00686612, 7.00342324,
       7.00342324, 7.00342324, 7.00008437, 6.9977766 , 6.9977766 ,
       6.99464629, 6.99464629, 6.99244361, 6.98899965, 6.98899965,
       6.98899965, 6.99505186, 7.00568978, 7.00463272, 7.00404082,
       7.00379741, 7.00331006, 6.99926902, 6.99443594, 6.99316198,
       6.98843291, 6.98450322, 7.00697282, 7.00394598, 6.99933206,
       6.99805701, 6.99678089, 6.9955053 , 6.9955053 , 6.99443827,
       6.99443827, 6.99178309, 6.98509313, 6.98509313, 6.98175372,
       6.97670514, 6.97805568, 7.02046285, 7.02046285, 7.02046285,
       7.02046285, 7.03273957, 7.03273957, 7.03273957, 7.03115986,
       7.03115986, 7.0281341 , 7.02187402, 7.02187402, 7.01864024,
       7.01864024, 7.01530191, 7.01103594, 7.00883326, 7.00883326,
       7.00883326, 7.00381284, 7.00057906, 7.00057906, 6.99827129,
       6.99514044, 6.99283267, 6.99283267, 8.03657833, 8.02415683,
       8.01062752, 7.99663624, 8.00520593, 7.99358201, 7.96373815,
       7.93252829, 7.93808518, 7.93308719, 8.0639918 , 8.05732536,
       8.02395902, 8.01554912, 8.25560658, 8.92289862])

In [15]:
#Prediction of memory utilization 
dfm=pd.read_csv("overallinfo.csv")
column_names=["time","cpu_utilization","processor_time","user_time","nice_time","idle_time","memory_utilization","used_mem","total_mem","free_mem","available_mem","pagetable","vmused","num_pages","pf_before","pf_persec","ps_in_persec","ps_out_psec","pread_persec","pwrite_persec","p_persec"]
dfm=pd.read_csv("overallinfo.csv",names=column_names)

In [16]:
dfm

,time,cpu_utilization,processor_time,user_time,nice_time,idle_time,memory_utilization,used_mem,total_mem,free_mem,...,pagetable,vmused,num_pages,pf_before,pf_persec,ps_in_persec,ps_out_psec,pread_persec,pwrite_persec,p_persec
0,Tue Dec 1 17:06:23 2020,7.0,139420,124233,552,1937853,40.0,1233236,2035520,90544,...,46752,17724,22636,9445613,0,0,0,0,0,0
1,Tue Dec 1 17:06:23 2020,7.0,139420,124233,552,1937853,40.0,1233236,2035520,90544,...,46752,17724,22636,9445613,0,0,0,0,0,0
2,Tue Dec 1 17:06:23 2020,7.0,139420,124233,552,1937853,40.0,1233236,2035520,90544,...,46752,17724,22636,9445613,0,0,0,0,0,0
3,Tue Dec 1 17:06:23 2020,7.0,139420,124233,552,1937853,40.0,1233236,2035520,90544,...,46752,17724,22636,9445613,0,0,0,0,0,0
4,Tue Dec 1 17:06:23 2020,7.0,139420,124233,552,1937853,40.0,1233236,2035520,90544,...,46752,17724,22636,9445613,5845,0,0,0,112,112
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
330,Tue Dec 1 19:27:34 2020,9.0,235595,210175,568,2677591,46.0,1111332,2035520,608668,...,44020,17236,152167,13611835,0,0,0,0,0,0
331,Tue Dec 1 19:27:34 2020,9.0,235595,210175,568,2677591,46.0,1111332,2035520,608668,...,44020,17236,152167,13611835,0,0,0,0,0,0
332,Tue Dec 1 19:27:34 2020,9.0,235595,210175,568,2677591,46.0,1111332,2035520,608668,...,44020,17236,152167,13611835,0,0,0,0,0,0
333,Tue Dec 1 19:27:34 2020,9.0,235595,210175,568,2677591,46.0,1111332,2035520,608668,...,44020,17236,152167,13611835,4564,0,0,8,1332,1340
334,Tue Dec 1 19:27:34 2020,9.0,235612,210189,568,2678068,46.0,1111320,2035520,608668,...,44020,17236,152102,13616399,0,0,0,0,0,0

In [17]:
dfm=dfm.drop(["time","cpu_utilization","processor_time","user_time","nice_time","idle_time"],axis=1)

In [18]:
dfm

,memory_utilization,used_mem,total_mem,free_mem,available_mem,pagetable,vmused,num_pages,pf_before,pf_persec,ps_in_persec,ps_out_psec,pread_persec,pwrite_persec,p_persec
0,40.0,1233236,2035520,90544,579984,46752,17724,22636,9445613,0,0,0,0,0,0
1,40.0,1233236,2035520,90544,579984,46752,17724,22636,9445613,0,0,0,0,0,0
2,40.0,1233236,2035520,90544,579984,46752,17724,22636,9445613,0,0,0,0,0,0
3,40.0,1233236,2035520,90544,579984,46752,17724,22636,9445613,0,0,0,0,0,0
4,40.0,1233236,2035520,90544,579984,46752,17724,22636,9445613,5845,0,0,0,112,112
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
330,46.0,1111332,2035520,608668,736692,44020,17236,152167,13611835,0,0,0,0,0,0
331,46.0,1111332,2035520,608668,736692,44020,17236,152167,13611835,0,0,0,0,0,0
332,46.0,1111332,2035520,608668,736692,44020,17236,152167,13611835,0,0,0,0,0,0
333,46.0,1111332,2035520,608668,736692,44020,17236,152167,13611835,4564,0,0,8,1332,1340
334,46.0,1111320,2035520,608668,736692,44020,17236,152102,13616399,0,0,0,0,0,0

In [19]:
dfm_copy=dfm.copy()
training_data_mem=dfm_copy.sample(frac=0.75)
test_data_mem=dfm_copy.drop(training_data_mem.index)

In [20]:
training_data_mem

,memory_utilization,used_mem,total_mem,free_mem,available_mem,pagetable,vmused,num_pages,pf_before,pf_persec,ps_in_persec,ps_out_psec,pread_persec,pwrite_persec,p_persec
298,36.0,1315364,2035520,97880,533696,47096,17540,18690,12033417,8174,0,0,1112,1904,3016
200,42.0,1180648,2035520,164248,611708,46024,17596,46302,9792985,0,0,0,0,0,0
58,40.0,1230280,2035520,90756,583292,46512,17580,22687,9537312,1416,0,0,0,40,40
107,42.0,1193480,2035520,172788,619888,45932,17596,43197,9668622,3601,0,0,0,56,56
213,43.0,1179236,2035520,164248,611708,46024,17596,46648,9809877,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,38.0,1271432,2035520,183476,519960,45996,17380,45869,12416654,148741,3,388,268,6900,7168
192,43.0,1180220,2035520,164248,611708,46024,17596,46415,9787419,0,0,0,0,0,0
191,43.0,1180052,2035520,164248,611708,46024,17596,46459,9781767,5652,0,0,0,52,52
287,36.0,1303156,2035520,97880,533696,47096,17540,30893,11886338,6603,0,0,0,1884,1884
299,36.0,1317080,2035520,97880,533696,47096,17540,19048,12041591,4811,1,0,4,1416,1420

In [21]:
test_data_mem=test_data_mem.drop(["memory_utilization"],axis=1)
test_data_mem

,used_mem,total_mem,free_mem,available_mem,pagetable,vmused,num_pages,pf_before,pf_persec,ps_in_persec,ps_out_psec,pread_persec,pwrite_persec,p_persec
0,1233236,2035520,90544,579984,46752,17724,22636,9445613,0,0,0,0,0,0
3,1233236,2035520,90544,579984,46752,17724,22636,9445613,0,0,0,0,0,0
10,1231924,2035520,89520,581320,46596,17676,22378,9458419,0,0,0,0,0,0
13,1232152,2035520,89520,581320,46596,17676,22315,9464042,0,0,0,0,0,0
14,1232152,2035520,89520,581320,46596,17676,22315,9464042,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,1303520,2035520,79736,479452,47996,17716,17400,12283585,18596,4,105,16,2792,2808
319,1306396,2035520,79736,479452,47996,17716,21166,12309845,5875,0,0,0,1256,1256
327,1520792,2035520,102380,205064,62652,19876,31295,13326652,24778,5,0,488,3952,4440
329,1531900,2035520,102380,205064,62652,19876,23928,13458111,39180,973,6808,15892,31048,46940
331,1111332,2035520,608668,736692,44020,17236,152167,13611835,0,0,0,0,0,0

In [22]:
X=training_data_mem[["used_mem","total_mem","free_mem","available_mem","pagetable","vmused","num_pages","pf_before","pf_persec","ps_in_persec","ps_out_psec","pread_persec","pwrite_persec","p_persec"]]
y=training_data_mem["memory_utilization"]

In [23]:
reg_model=linear_model.LinearRegression()

In [24]:
reg.fit(X,y)

LinearRegression()

In [25]:
final_prediction=reg.predict(test_data_mem)

In [26]:
final_prediction

array([40.05191746, 40.05191746, 40.05919594, 40.04937527, 40.04937527,
       40.04937527, 40.05150921, 40.06662211, 40.01765291, 40.03096112,
       39.99925294, 39.99026716, 39.99026716, 39.98654676, 39.94218096,
       39.94218096, 40.02126812, 40.01064619, 39.9715712 , 39.94689891,
       40.03238773, 40.02923181, 40.01300213, 40.02602142, 41.97248051,
       41.97248051, 41.96554827, 41.80725458, 41.85619889, 41.8644312 ,
       41.85496413, 41.83890959, 41.83792895, 41.82951871, 41.80454863,
       41.81035001, 41.89395798, 41.88856196, 41.89461972, 41.89400338,
       41.89074421, 41.52988741, 41.52054551, 42.63703934, 42.7323605 ,
       42.7323605 , 42.63547907, 42.65131006, 42.68068345, 42.68068345,
       42.65370593, 42.64408775, 42.64408775, 42.65730772, 42.76889807,
       42.76889807, 42.73418389, 42.84377213, 42.82739889, 42.80591892,
       42.80591892, 42.76133047, 42.7351212 , 42.70617278, 42.70617278,
       42.70617278, 37.43619747, 37.8922006 , 37.78301999, 37.6455692 ,
       37.4946968 , 36.9911718 , 37.01422773, 36.45478584, 35.71547203,
       36.45097855, 36.45367724, 36.44145418, 36.67082898, 36.4597055 ,
       36.30132495, 25.47441693, 26.61693399, 46.02131169])